language: bash

services:
  - docker

env:
  matrix:
    - ALPINE_VER=3.8 TAGS=3.8,3,latest
    - ALPINE_VER=3.7 TAGS=3.7
    - ALPINE_VER=3.6 TAGS=3.6
    - ALPINE_VER=3.8 TAGS=3.8-dev,3-dev,dev ALPINE_DEV=1

script:
  - make && make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"
